---
abstract: 'PSGI handler on AnyEvent::SCGI'
author:
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
  Test::Requires: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.95'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Handler-AnyEvent-SCGI
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  AnyEvent::SCGI: 0
  Plack: 0.9901
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/miyagawa/Plack-Handler-AnyEvent-SCGI.git
version: 0.02
