---
abstract: 'PSGI handler on AnyEvent::SCGI'
author:
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
build_requires:
  ExtUtils::MakeMaker: '6.42'
  Test::More: '0'
  Test::Requires: '0'
configure_requires:
  Module::Build::Tiny: '0.039'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.024, Dist::Milla version v1.0.8, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Plack-Handler-AnyEvent-SCGI
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  AnyEvent::SCGI: '0'
  Plack: '0.9901'
  perl: '5.008001'
resources:
  bugtracker: https://github.com/miyagawa/Plack-Handler-AnyEvent-SCGI/issues
  homepage: https://github.com/miyagawa/Plack-Handler-AnyEvent-SCGI
  repository: https://github.com/miyagawa/Plack-Handler-AnyEvent-SCGI.git
version: '0.03'
